# Homework 1

This homework has a *theory* and a *practical* part. 
To answer your theory questions, you can use the cells I have added below the questions. These are already marked as `Markdown` cells, so when you run them or press `Shift + Return`, you should just get formatted text. 

### Why is Python a useful tool for Data Analytics?

Your answer: Its useful for data science because of its active development and support of third-party packages!

### Give one example of when you would use Pandas, NumPy and SciKit

Pandas:Useful for manipulation of heterogeneous and labeled data!

NumPy: Useful for manipulation of homogeneous array-based data!

SciKit:Useful for machine learning applications:Classification,Regression,Clustering...

The next part of your assigment is to write Python code to complete the specified tasks.

### 1. Create a Dictionary with the terms that you can find in the Glossary in CourseWeb. 

This dictionary should be named __Glossary__. 
When you type the Glossary['any term here'] you should obtain the definiton of that term. For example, if I type Glossary['Python'] my output should be 'A high-level, general-purpose programming language'.


{'Python': 'A high-level, general-purpose programming language'}
A high-level, general-purpose programming language


### 2. Creating and Slicing Lists

In [4]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
# define example
data = pd.read_csv("train.csv",usecols=[2])
values = array(data)
#print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
#print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
#print(inverted)


[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]


D:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
